name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    pull_request:
      types:
        - opened

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Build tester
        run: cicd/jobs/setup/build-tester.sh

      - name: Run unit tests
        run: cicd/jobs/test/run-unit-tests.sh

      - name: Run style tests
        run: cicd/jobs/test/run-style-tests.sh

      - name: Upload coverage to Codecov
        run: cicd/jobs/test/run-upload-codecov.sh
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
